from .constants import COUNTRY_CODE, years

paths = {
    "eurostat_raw": "../data/raw/nrg_bal_peh_el_prod_by_fuel.tsv",
    "da_import_FR": f"../data/intermediate/da_import_FR_{years}.csv",
    "da_export_FR": f"../data/intermediate/da_export_FR_{years}.csv",
    "net_export_FR": f"../data/intermediate/net_export_FR_{years}.csv",
    "da_import_ES": f"../data/intermediate/da_import_ES_{years}.csv",
    "da_export_ES": f"../data/intermediate/da_export_ES_{years}.csv",
    "net_export_ES": f"../data/intermediate/net_export_ES_{years}.csv",
    "gas_price_raw": "../data/raw/Price+History_20241019_2220.xlsx",
    "gas_price_MIBGAS_raw": "../data/raw/MIBGAS/",
    "gas_price": f"../data/intermediate/gas_price_{years}.csv",
    "carbon_price": f"../data/intermediate/carbon_price_{years}.csv",
    "carbon_price_raw": "../data/raw/carbonprice.csv",
    "gas_dependency": f"../data/raw/nrg_bal_peh_el_prod_by_fuel.tsv",
    "european_prices_da_intermediate": f"../data/intermediate/european_prices_da_intermediate.csv",
    "european_prices_da": f"../data/processed/european_prices_da.csv",
    "renew_FR": f"../data/intermediate/renew_FR_{years}.csv",
    "load_da_FR": f"../data/intermediate/load_da_FR_{years}.csv",
    "load_real_FR": f"../data/intermediate/load_real_FR_{years}.csv",
    "generation_FR": f"../data/intermediate/gen_FR_{years}.csv",
    "renew_ES": f"../data/intermediate/renew_ES_{years}.csv",
    "load_da_ES": f"../data/intermediate/load_da_ES_{years}.csv",
    "load_real_ES": f"../data/intermediate/load_real_ES_{years}.csv",
    "generation_ES": f"../data/intermediate/gen_ES_{years}.csv",
    "res_load_da": f"../data/intermediate/res_load_da_{years}.csv",
    "installed_cap_raw_FR_2018_2020": f"../data/raw/ENTSO-E/installed_capacity_per_type_FR_2018_2020.csv",
    "installed_cap_raw_FR_2021_2023": f"../data/raw/ENTSO-E/installed_capacity_per_type_FR_2021_2023.csv",
    "installed_capacity_FR": f"../data/intermediate/installed_capacity_FR_{years}.csv",
    "na_gen_unavail_rte_raw_FR": "../data/raw/nuclear_rte/ProductionUnavailability.csv",
    "na_rte_FR": "../data/intermediate/nuclear_avail_rte_FR.csv",
    "na_gen_unavail_esios_raw_ES": "../data/raw/nuclear_esios/nuclear_esios.csv",
    "na_esios_ES": "../data/intermediate/nuclear_avail_esio_ES.csv",
    "filling_rate_raw_FR_2018_2020": f"../data/raw/ENTSO-E/filling_rate_FR_2018_2020.csv",
    "filling_rate_raw_FR_2021_2023": f"../data/raw/ENTSO-E/filling_rate_FR_2021_2023.csv",
    "filling_rate_raw_ES_2018_2020": f"../data/raw/ENTSO-E/filling_rate_ES_2018_2020.csv",
    "filling_rate_raw_ES_2021_2023": f"../data/raw/ENTSO-E/filling_rate_ES_2021_2023.csv",
    "filling_rate_FR": f"../data/intermediate/filling_rate_FR_{years}.csv",
    "filling_rate_ES": f"../data/intermediate/filling_rate_ES_{years}.csv",
    "river_temp_FR": f"../data/intermediate/river_temp_mean_FR_{years}.csv",
    "river_flow_FR": f"../data/intermediate/river_flow_FR_{years}.csv",
    "river_temp_ES_raw": f"../data/raw/DatosHistoricos_Ebro_temp",
    "river_temp_ES": f"../data/intermediate/river_temp_mean_ES_{years}.csv",
    "river_flow_ES_raw": f"../data/raw/DatosHistoricos_Ebro_flow",
    "river_flow_ES": f"../data/intermediate/river_flow_ES_{years}.csv",
    "era5_wind_raw_FR": f"../data/raw/ERA5/wind_FR/data.grib",
    "era5_solar_temp_raw_FR": f"../data/raw/ERA5/solar_temp_FR/data.grib",
    "era5_wind_raw_ES": f"../data/raw/ERA5/wind_ES/data.grib",
    "era5_solar_temp_raw_ES": f"../data/raw/ERA5/solar_temp_ES/data.grib",
    "era5_wind_FR": f"../data/intermediate/era5_wind_FR_{years}.csv",
    "era5_solar_temp_FR": f"../data/intermediate/era5_solar_temp_FR_{years}.csv",
    "era5_wind_ES": f"../data/intermediate/era5_wind_ES_{years}.csv",
    "era5_solar_temp_ES": f"../data/intermediate/era5_solar_temp_ES_{years}.csv",
    "FR_holiday_raw": "../data/raw/france_holiday.csv",
    "FR_holiday": "../data/intermediate/france_holiday.csv",
    "ES_holiday_raw": "../data/raw/spain_holiday.xlsx",
    "calendrical_data": f"../data/intermediate/calendrical_data_{years}.csv",
    "data_full": f"../data/processed/data_full_{years}.csv",
    "data_selected": f"../data/processed/data_selected_{years}.csv",
}


model_paths = f"models/"
