# This file contains the feature configuration for the Shapley flow analysis, 
# including the list of features, their types, and the edges in the causal graph 
# for each target variable. It also includes a mapping from feature names to more 
# human-readable names for visualization purposes.
# Further, it contains the constant value in MW for nuclear availability in France, 
# which is used in the "what-if" scenario analysis.

edges_FR_price = [('hour_sin', 'rl_BE'), ('hour_sin', 'rl_ES'), ('hour_sin', 'rl_DE_LU'), ('hour_sin', 'rl_IT_NORD'), ('hour_sin', 'load_da_FR'), ('hour_sin', 'nuclear_avail_rte_FR'), ('hour_sin', 'ssrd_FR'), ('hour_sin', 'wind_speed_100m_FR'), ('hour_sin', 'air_temp_era5_FR'), ('hour_cos', 'rl_BE'), ('hour_cos', 'rl_ES'), ('hour_cos', 'rl_DE_LU'), ('hour_cos', 'rl_IT_NORD'), ('hour_cos', 'load_da_FR'), ('hour_cos', 'nuclear_avail_rte_FR'), ('hour_cos', 'ssrd_FR'), ('hour_cos', 'wind_speed_100m_FR'), ('hour_cos', 'air_temp_era5_FR'), ('day_of_year_sin', 'rl_BE'), ('day_of_year_sin', 'rl_ES'), ('day_of_year_sin', 'rl_DE_LU'), ('day_of_year_sin', 'rl_IT_NORD'), ('day_of_year_sin', 'load_da_FR'), ('day_of_year_sin', 'nuclear_avail_rte_FR'), ('day_of_year_sin', 'ssrd_FR'), ('day_of_year_sin', 'wind_speed_100m_FR'), ('day_of_year_sin', 'air_temp_era5_FR'), ('day_of_year_cos', 'rl_BE'), ('day_of_year_cos', 'rl_ES'), ('day_of_year_cos', 'rl_DE_LU'), ('day_of_year_cos', 'rl_IT_NORD'), ('day_of_year_cos', 'load_da_FR'), ('day_of_year_cos', 'nuclear_avail_rte_FR'), ('day_of_year_cos', 'ssrd_FR'), ('day_of_year_cos', 'wind_speed_100m_FR'), ('day_of_year_cos', 'air_temp_era5_FR'), ('isworkingday_FR', 'rl_BE'), ('isworkingday_FR', 'rl_ES'), ('isworkingday_FR', 'rl_DE_LU'), ('isworkingday_FR', 'rl_IT_NORD'), ('isworkingday_FR', 'load_da_FR'), ('isworkingday_FR', 'nuclear_avail_rte_FR'), ('air_temp_era5_FR', 'river_temp_FR'), ('air_temp_era5_FR', 'rl_BE'), ('air_temp_era5_FR', 'rl_ES'), ('air_temp_era5_FR', 'rl_DE_LU'), ('air_temp_era5_FR', 'rl_IT_NORD'), ('air_temp_era5_FR', 'load_da_FR'), ('air_temp_era5_FR', 'solar_da_FR'), ('air_temp_era5_FR', 'filling_rate_FR'), ('rl_BE', 'price_da_FR'), ('rl_ES', 'price_da_FR'), ('rl_DE_LU', 'price_da_FR'), ('rl_IT_NORD', 'price_da_FR'), ('load_da_FR', 'price_da_FR'), ('nuclear_avail_rte_FR', 'price_da_FR'), ('run_off_gen_FR', 'price_da_FR'), ('solar_da_FR', 'price_da_FR'), ('wind_da_FR', 'price_da_FR'), ('carbon_price_FR', 'price_da_FR'), ('gas_price_FR', 'price_da_FR'), ('filling_rate_FR', 'price_da_FR'), ('ssrd_FR', 'solar_da_FR'), ('wind_speed_100m_FR', 'wind_da_FR'), ('ssrd_FR', 'rl_BE'), ('ssrd_FR', 'rl_ES'), ('ssrd_FR', 'rl_DE_LU'), ('ssrd_FR', 'rl_IT_NORD'), ('wind_speed_100m_FR', 'rl_BE'), ('wind_speed_100m_FR', 'rl_ES'), ('wind_speed_100m_FR', 'rl_DE_LU'), ('wind_speed_100m_FR', 'rl_IT_NORD'), ('river_temp_FR', 'nuclear_avail_rte_FR'), ('river_temp_FR', 'run_off_gen_FR'), ('river_temp_FR', 'filling_rate_FR'), ('river_flow_mean_FR', 'nuclear_avail_rte_FR'), ('river_flow_mean_FR', 'run_off_gen_FR'), ('river_flow_mean_FR', 'filling_rate_FR'), ('day_of_year_sin', 'river_temp_FR'), ('day_of_year_sin', 'river_flow_mean_FR'), ('day_of_year_sin', 'filling_rate_FR'), ('day_of_year_sin', 'gas_price_FR'), ('day_of_year_cos', 'river_temp_FR'), ('day_of_year_cos', 'river_flow_mean_FR'), ('day_of_year_cos', 'filling_rate_FR'), ('day_of_year_cos', 'gas_price_FR'), ('year', 'carbon_price_FR'), ('year', 'gas_price_FR'), ('year', 'rl_BE'), ('year', 'rl_ES'), ('year', 'rl_DE_LU'), ('year', 'rl_IT_NORD'), ('year', 'load_da_FR'), ('year', 'ssrd_FR'), ('year', 'wind_speed_100m_FR'), ('year', 'air_temp_era5_FR'), ('year', 'river_temp_FR'), ('year', 'river_flow_mean_FR'), ('year', 'solar_da_FR'), ('year', 'wind_da_FR'), ('year', 'nuclear_avail_rte_FR'), ('year', 'run_off_gen_FR'), ('nuclear_avail_esios_ES', 'price_da_FR'), ('year', 'nuclear_avail_esios_ES'), ('hour_sin', 'nuclear_avail_esios_ES'), ('hour_cos', 'nuclear_avail_esios_ES'), ('day_of_year_sin', 'nuclear_avail_esios_ES'), ('day_of_year_cos', 'nuclear_avail_esios_ES'), ('isworkingday_FR', 'nuclear_avail_esios_ES')]
edges_FR_export = [('hour_sin', 'rl_BE'), ('hour_sin', 'rl_ES'), ('hour_sin', 'rl_DE_LU'), ('hour_sin', 'rl_IT_NORD'), ('hour_sin', 'load_da_FR'), ('hour_sin', 'nuclear_avail_rte_FR'), ('hour_sin', 'ssrd_FR'), ('hour_sin', 'wind_speed_100m_FR'), ('hour_sin', 'air_temp_era5_FR'), ('hour_cos', 'rl_BE'), ('hour_cos', 'rl_ES'), ('hour_cos', 'rl_DE_LU'), ('hour_cos', 'rl_IT_NORD'), ('hour_cos', 'load_da_FR'), ('hour_cos', 'nuclear_avail_rte_FR'), ('hour_cos', 'ssrd_FR'), ('hour_cos', 'wind_speed_100m_FR'), ('hour_cos', 'air_temp_era5_FR'), ('day_of_year_sin', 'rl_BE'), ('day_of_year_sin', 'rl_ES'), ('day_of_year_sin', 'rl_DE_LU'), ('day_of_year_sin', 'rl_IT_NORD'), ('day_of_year_sin', 'load_da_FR'), ('day_of_year_sin', 'nuclear_avail_rte_FR'), ('day_of_year_sin', 'ssrd_FR'), ('day_of_year_sin', 'wind_speed_100m_FR'), ('day_of_year_sin', 'air_temp_era5_FR'), ('day_of_year_cos', 'rl_BE'), ('day_of_year_cos', 'rl_ES'), ('day_of_year_cos', 'rl_DE_LU'), ('day_of_year_cos', 'rl_IT_NORD'), ('day_of_year_cos', 'load_da_FR'), ('day_of_year_cos', 'nuclear_avail_rte_FR'), ('day_of_year_cos', 'ssrd_FR'), ('day_of_year_cos', 'wind_speed_100m_FR'), ('day_of_year_cos', 'air_temp_era5_FR'), ('isworkingday_FR', 'rl_BE'), ('isworkingday_FR', 'rl_ES'), ('isworkingday_FR', 'rl_DE_LU'), ('isworkingday_FR', 'rl_IT_NORD'), ('isworkingday_FR', 'load_da_FR'), ('isworkingday_FR', 'nuclear_avail_rte_FR'), ('air_temp_era5_FR', 'river_temp_FR'), ('air_temp_era5_FR', 'rl_BE'), ('air_temp_era5_FR', 'rl_ES'), ('air_temp_era5_FR', 'rl_DE_LU'), ('air_temp_era5_FR', 'rl_IT_NORD'), ('air_temp_era5_FR', 'load_da_FR'), ('air_temp_era5_FR', 'solar_da_FR'), ('air_temp_era5_FR', 'filling_rate_FR'), ('rl_BE', 'net_export_FR'), ('rl_ES', 'net_export_FR'), ('rl_DE_LU', 'net_export_FR'), ('rl_IT_NORD', 'net_export_FR'), ('load_da_FR', 'net_export_FR'), ('nuclear_avail_rte_FR', 'net_export_FR'), ('run_off_gen_FR', 'net_export_FR'), ('solar_da_FR', 'net_export_FR'), ('wind_da_FR', 'net_export_FR'), ('carbon_price_FR', 'net_export_FR'), ('gas_price_FR', 'net_export_FR'), ('filling_rate_FR', 'net_export_FR'), ('ssrd_FR', 'solar_da_FR'), ('wind_speed_100m_FR', 'wind_da_FR'), ('ssrd_FR', 'rl_BE'), ('ssrd_FR', 'rl_ES'), ('ssrd_FR', 'rl_DE_LU'), ('ssrd_FR', 'rl_IT_NORD'), ('wind_speed_100m_FR', 'rl_BE'), ('wind_speed_100m_FR', 'rl_ES'), ('wind_speed_100m_FR', 'rl_DE_LU'), ('wind_speed_100m_FR', 'rl_IT_NORD'), ('river_temp_FR', 'nuclear_avail_rte_FR'), ('river_temp_FR', 'run_off_gen_FR'), ('river_temp_FR', 'filling_rate_FR'), ('river_flow_mean_FR', 'nuclear_avail_rte_FR'), ('river_flow_mean_FR', 'run_off_gen_FR'), ('river_flow_mean_FR', 'filling_rate_FR'), ('day_of_year_sin', 'river_temp_FR'), ('day_of_year_sin', 'river_flow_mean_FR'), ('day_of_year_sin', 'filling_rate_FR'), ('day_of_year_sin', 'gas_price_FR'), ('day_of_year_cos', 'river_temp_FR'), ('day_of_year_cos', 'river_flow_mean_FR'), ('day_of_year_cos', 'filling_rate_FR'), ('day_of_year_cos', 'gas_price_FR'), ('year', 'carbon_price_FR'), ('year', 'gas_price_FR'), ('year', 'rl_BE'), ('year', 'rl_ES'), ('year', 'rl_DE_LU'), ('year', 'rl_IT_NORD'), ('year', 'load_da_FR'), ('year', 'ssrd_FR'), ('year', 'wind_speed_100m_FR'), ('year', 'air_temp_era5_FR'), ('year', 'river_temp_FR'), ('year', 'river_flow_mean_FR'), ('year', 'solar_da_FR'), ('year', 'wind_da_FR'), ('year', 'nuclear_avail_rte_FR'), ('year', 'run_off_gen_FR'), ('nuclear_avail_esios_ES', 'net_export_FR'), ('year', 'nuclear_avail_esios_ES'), ('hour_sin', 'nuclear_avail_esios_ES'), ('hour_cos', 'nuclear_avail_esios_ES'), ('day_of_year_sin', 'nuclear_avail_esios_ES'), ('day_of_year_cos', 'nuclear_avail_esios_ES'), ('isworkingday_FR', 'nuclear_avail_esios_ES')]
edges_ES_price = [('hour_sin', 'rl_FR'), ('hour_sin', 'rl_PT'), ('hour_sin', 'load_da_ES'), ('hour_sin', 'nuclear_avail_esios_ES'), ('hour_sin', 'ssrd_ES'), ('hour_sin', 'wind_speed_100m_ES'), ('hour_sin', 'air_temp_era5_ES'), ('hour_cos', 'rl_FR'), ('hour_cos', 'rl_PT'), ('hour_cos', 'load_da_ES'), ('hour_cos', 'nuclear_avail_esios_ES'), ('hour_cos', 'ssrd_ES'), ('hour_cos', 'wind_speed_100m_ES'), ('hour_cos', 'air_temp_era5_ES'), ('day_of_year_sin', 'rl_FR'), ('day_of_year_sin', 'rl_PT'), ('day_of_year_sin', 'load_da_ES'), ('day_of_year_sin', 'nuclear_avail_esios_ES'), ('day_of_year_sin', 'ssrd_ES'), ('day_of_year_sin', 'wind_speed_100m_ES'), ('day_of_year_sin', 'air_temp_era5_ES'), ('day_of_year_cos', 'rl_FR'), ('day_of_year_cos', 'rl_PT'), ('day_of_year_cos', 'load_da_ES'), ('day_of_year_cos', 'nuclear_avail_esios_ES'), ('day_of_year_cos', 'ssrd_ES'), ('day_of_year_cos', 'wind_speed_100m_ES'), ('day_of_year_cos', 'air_temp_era5_ES'), ('isworkingday_ES', 'rl_FR'), ('isworkingday_ES', 'rl_PT'), ('isworkingday_ES', 'load_da_ES'), ('isworkingday_ES', 'nuclear_avail_esios_ES'), ('air_temp_era5_ES', 'river_temp_ES'), ('air_temp_era5_ES', 'rl_FR'), ('air_temp_era5_ES', 'rl_PT'), ('air_temp_era5_ES', 'load_da_ES'), ('air_temp_era5_ES', 'solar_da_ES'), ('air_temp_era5_ES', 'filling_rate_ES'), ('rl_FR', 'price_da_ES'), ('rl_PT', 'price_da_ES'), ('load_da_ES', 'price_da_ES'), ('nuclear_avail_esios_ES', 'price_da_ES'), ('run_off_gen_ES', 'price_da_ES'), ('solar_da_ES', 'price_da_ES'), ('wind_da_ES', 'price_da_ES'), ('carbon_price_ES', 'price_da_ES'), ('gas_price_ES', 'price_da_ES'), ('filling_rate_ES', 'price_da_ES'), ('ssrd_ES', 'solar_da_ES'), ('wind_speed_100m_ES', 'wind_da_ES'), ('ssrd_ES', 'rl_FR'), ('ssrd_ES', 'rl_PT'), ('wind_speed_100m_ES', 'rl_FR'), ('wind_speed_100m_ES', 'rl_PT'), ('river_temp_ES', 'nuclear_avail_esios_ES'), ('river_temp_ES', 'run_off_gen_ES'), ('river_temp_ES', 'filling_rate_ES'), ('river_flow_mean_ES', 'nuclear_avail_esios_ES'), ('river_flow_mean_ES', 'run_off_gen_ES'), ('river_flow_mean_ES', 'filling_rate_ES'), ('day_of_year_sin', 'river_temp_ES'), ('day_of_year_sin', 'river_flow_mean_ES'), ('day_of_year_sin', 'filling_rate_ES'), ('day_of_year_sin', 'gas_price_ES'), ('day_of_year_cos', 'river_temp_ES'), ('day_of_year_cos', 'river_flow_mean_ES'), ('day_of_year_cos', 'filling_rate_ES'), ('day_of_year_cos', 'gas_price_ES'), ('year', 'carbon_price_ES'), ('year', 'gas_price_ES'), ('year', 'rl_FR'), ('year', 'rl_PT'), ('year', 'load_da_ES'), ('year', 'ssrd_ES'), ('year', 'wind_speed_100m_ES'), ('year', 'air_temp_era5_ES'), ('year', 'river_temp_ES'), ('year', 'river_flow_mean_ES'), ('year', 'solar_da_ES'), ('year', 'wind_da_ES'), ('year', 'nuclear_avail_esios_ES'), ('year', 'run_off_gen_ES'), ('nuclear_avail_rte_FR', 'price_da_ES'), ('year', 'nuclear_avail_rte_FR'), ('hour_sin', 'nuclear_avail_rte_FR'), ('hour_cos', 'nuclear_avail_rte_FR'), ('day_of_year_sin', 'nuclear_avail_rte_FR'), ('day_of_year_cos', 'nuclear_avail_rte_FR'), ('isworkingday_ES', 'nuclear_avail_rte_FR')]

target_names = ['FR_price', 'FR_export', 'ES_price']
calendar_features = ['hour_sin', 'hour_cos', 'day_of_year_sin', 'day_of_year_cos', 'isworkingday_FR', 'isworkingday_ES', 'year']
meteorological_features = ['air_temp_era5_FR', 'air_temp_era5_ES', 'ssrd_FR', 'ssrd_ES', 'wind_speed_100m_FR', 'wind_speed_100m_ES', 'river_temp_FR', 'river_temp_ES', 'river_flow_mean_FR', 'river_flow_mean_ES']
energy_features = ['rl_BE', 'rl_FR', 'rl_PT', 'rl_ES', 'rl_DE_LU', 'rl_IT_NORD', 'load_da_FR', 'load_da_ES', 'nuclear_avail_rte_FR', 'nuclear_avail_esios_ES', 'solar_da_FR', 'solar_da_ES', 'filling_rate_FR', 'filling_rate_ES', 'run_off_gen_FR', 'run_off_gen_ES', 'wind_da_FR', 'wind_da_ES', 'carbon_price_FR', 'carbon_price_ES', 'gas_price_FR', 'gas_price_ES']

paper_rename_dict = {
    'hour_sin': 'Hour (sin)',
    'rl_BE': 'RL BE',
    'rl_FR': 'RL FR',
    'rl_PT': 'RL PT',
    'rl_ES': 'RL ES',
    'rl_DE_LU': 'RL DE-LU',
    'rl_IT_NORD': 'RL IT-North',
    'load_da_FR': 'Load day-ahead FR',
    'load_da_ES': 'Load day-ahead ES',
    'nuclear_avail_rte_FR': 'Nuclear availability FR',
    'nuclear_avail_esios_ES': 'Nuclear availability ES',
    'ssrd_FR': 'Surface solar radiation downwards FR',
    'ssrd_ES': 'Surface solar radiation downwards ES',
    'wind_speed_100m_FR': '100 m Wind speed FR',
    'wind_speed_100m_ES': '100 m Wind speed ES',
    'air_temp_era5_FR': 'Air temperature FR',
    'air_temp_era5_ES': 'Air temperature ES',
    'hour_cos': 'Hour (cos)',
    'day_of_year_sin': 'Day of year (sin)',
    'day_of_year_cos': 'Day of year (cos)',
    'isworkingday_FR': 'Is Working Day FR?',
    'isworkingday_ES': 'Is Working Day ES?',
    'river_temp_FR': 'River temperature FR',
    'river_temp_ES': 'River temperature ES',
    'solar_da_FR': 'Solar day-ahead FR',
    'solar_da_ES': 'Solar day-ahead ES',
    'filling_rate_FR': 'Filling rate FR',
    'filling_rate_ES': 'Filling rate ES',
    'price_da_FR': 'Price day-ahead FR',
    'price_da_ES': 'Price day-ahead ES',
    'net_export_FR': 'Net exports FR',
    'run_off_gen_FR': 'ROR generation FR',
    'run_off_gen_ES': 'ROR generation ES',
    'wind_da_FR': 'Wind day-ahead FR',
    'wind_da_ES': 'Wind day-ahead ES',
    'carbon_price_FR': 'Carbon price FR',
    'carbon_price_ES': 'Carbon price ES',
    'gas_price_FR': 'Gas price FR',
    'gas_price_ES': 'Gas price ES',
    'river_flow_mean_FR': 'River flow rate FR',
    'river_flow_mean_ES': 'River flow rate ES',
    'year': 'Year',
    'FR_price': 'Price day-ahead FR',
    'FR_export': 'Net exports FR',
    'ES_price': 'Price day-ahead ES',
    'ES_export': 'Net exports ES',
}

paper_rename_dict_including_units = {
    'hour_sin': 'Hour (sin)',
    'rl_BE': 'RL BE (GW)',
    'rl_FR': 'RL FR (GW)',
    'rl_PT': 'RL PT (GW)',
    'rl_ES': 'RL ES (GW)',
    'rl_DE_LU': 'RL DE-LU (GW)',
    'rl_IT_NORD': 'RL IT-North (GW)',
    'load_da_FR': 'Load day-ahead FR (GW)',
    'load_da_ES': 'Load day-ahead ES (GW)',
    'nuclear_avail_rte_FR': 'Nuclear availability FR (GW)',
    'nuclear_avail_esios_ES': 'Nuclear availability ES (GW)',
    'ssrd_FR': 'Surface solar radiation downwards FR (GW)',
    'ssrd_ES': 'Surface solar radiation downwards ES (GW)',
    'wind_speed_100m_FR': '100 m Wind speed FR (m/s)',
    'wind_speed_100m_ES': '100 m Wind speed ES (m/s)',
    'air_temp_era5_FR': 'Air temperature FR (°C)',
    'air_temp_era5_ES': 'Air temperature ES (°C)',
    'hour_cos': 'Hour (cos)',
    'day_of_year_sin': 'Day of year (sin)',
    'day_of_year_cos': 'Day of year (cos)',
    'isworkingday_FR': 'Is Working Day FR?',
    'isworkingday_ES': 'Is Working Day ES?',
    'river_temp_FR': 'River temperature FR (°C)',
    'river_temp_ES': 'River temperature ES (°C)',
    'solar_da_FR': 'Solar day-ahead FR (GW)',
    'solar_da_ES': 'Solar day-ahead ES (GW)',
    'filling_rate_FR': 'Filling rate FR (%)',
    'filling_rate_ES': 'Filling rate ES (%)',
    'price_da_FR': 'Price day-ahead FR (EUR/MWh)',
    'price_da_ES': 'Price day-ahead ES (EUR/MWh)',
    'net_export_FR': 'Net exports FR (GW)',
    'run_off_gen_FR': 'ROR generation FR (GW)',
    'run_off_gen_ES': 'ROR generation ES (GW)',
    'wind_da_FR': 'Wind day-ahead FR (GW)',
    'wind_da_ES': 'Wind day-ahead ES (GW)',
    'carbon_price_FR': 'Carbon price FR (EUR/tCO2)',
    'carbon_price_ES': 'Carbon price ES (EUR/tCO2)',
    'gas_price_FR': 'Gas price FR (EUR/MWh)',
    'gas_price_ES': 'Gas price ES (EUR/MWh)',
    'river_flow_mean_FR': 'River flow rate FR (m³/s)',
    'river_flow_mean_ES': 'River flow rate ES (m³/s)',
    'year': 'Year',
    'FR_price': 'Price day-ahead FR (EUR/MWh)',
    'FR_export': 'Net exports FR (GW)',
    'ES_price': 'Price day-ahead ES (EUR/MWh)',
    'ES_export': 'Net exports ES (GW)',
}

paper_rename_dict_inverse = {v: k for k, v in paper_rename_dict.items()}

feature_list_FR_price = ['Air temperature FR',
 'Carbon price FR',
 'Filling rate FR',
 'Gas price FR',
 'Load day-ahead FR',
 'Nuclear availability ES',
 'Nuclear availability FR',
 'Price day-ahead FR',
 'River flow rate FR',
 'River temperature FR',
 'RL BE',
 'RL DE-LU',
 'RL ES',
 'RL IT-North',
 'ROR generation FR',
 'Solar day-ahead FR',
 'Surface solar radiation downwards FR',
 'Wind day-ahead FR',
 '100 m Wind speed FR'
]
feature_list_FR_export = ['Air temperature FR',
 'Carbon price FR',
 'Filling rate FR',
 'Gas price FR',
 'Load day-ahead FR',
 'Net exports FR',
 'Nuclear availability ES',
 'Nuclear availability FR',
 'River flow rate FR',
 'River temperature FR',
 'RL BE',
 'RL DE-LU',
 'RL ES',
 'RL IT-North',
 'ROR generation FR',
 'Solar day-ahead FR',
 'Surface solar radiation downwards FR',
 'Wind day-ahead FR',
 '100 m Wind speed FR'
]
feature_list_ES_price = ['Air temperature ES',
 'Carbon price ES',
 'Filling rate ES',
 'Gas price ES',
 'Load day-ahead ES',
 'Nuclear availability ES',
 'Nuclear availability FR',
 'Price day-ahead ES',
 'River flow rate ES',
 'River temperature ES',
 'RL FR',
 'RL PT',
 'ROR generation ES',
 'Solar day-ahead ES',
 'Surface solar radiation downwards ES',
 'Wind day-ahead ES',
 '100 m Wind speed ES'
]

list_target_nodes = ['air_temp_era5_FR', 'carbon_price_FR',
       'filling_rate_FR', 'gas_price_FR', 'load_da_FR', 'nuclear_avail_esios_ES',
       'nuclear_avail_rte_FR', 'river_flow_mean_FR', 'river_temp_FR', 'rl_BE',
       'rl_DE_LU', 'rl_ES', 'rl_IT_NORD', 'run_off_gen_FR', 'solar_da_FR',
       'ssrd_FR', 'wind_da_FR', 'wind_speed_100m_FR',
       'air_temp_era5_ES', 'carbon_price_ES',
       'filling_rate_ES', 'gas_price_ES',  'load_da_ES', 'nuclear_avail_esios_ES',
       'nuclear_avail_rte_FR', 'river_flow_mean_ES', 'river_temp_ES', 'rl_FR',
       'rl_PT', 'run_off_gen_ES', 'solar_da_ES', 'ssrd_ES', 'wind_da_ES',
       'wind_speed_100m_ES']

# constant added to nuclear availability features for what-if scenario analysis; 
# number in MW, this is just a hypothetical number to show the potential impact of increased nuclear availability
additional_nuc_avail = 10000 